volumes:
  prop-pulse-data:
    driver: local

networks:
  prop-pulse-network:
    driver: bridge

services:
  prop-pulse-postgres:
    image: postgres:16
    volumes:
      - prop-pulse-data:/var/lib/postgresql/data
    networks:
      - prop-pulse-network 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  prop-pulse-backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: ghcr.io/aditjain01/prop-pulse-backend:cdbdd2d 
    networks:
      - prop-pulse-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@prop-pulse-postgres:5432/postgres
    depends_on:
      prop-pulse-postgres:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s   
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prop-pulse-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ghcr.io/aditjain01/prop-pulse-ui:cdbdd2d 
    networks:
      - prop-pulse-network
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    environment:
      - VITE_BACKEND_URL=http://prop-pulse-backend:8000
    depends_on:
      - prop-pulse-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
