"""Loan model update

Revision ID: a20637df15eb
Revises: afc7858f2028
Create Date: 2025-04-07 15:04:15.199788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20637df15eb'
down_revision: Union[str, None] = 'afc7858f2028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'total_disbursed_amount')
    op.alter_column('payments', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('loans', sa.Column('total_disbursed_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
