"""Loan name change to loan number

Revision ID: 7f8c186ee3c7
Revises: a20637df15eb
Create Date: 2025-04-07 15:22:02.523275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8c186ee3c7'
down_revision: Union[str, None] = 'a20637df15eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('loan_number', sa.String(), nullable=True))
    op.alter_column('loans', 'institution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'sanction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('loans', 'sanction_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('loans', 'interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('loans', 'tenure_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('loans', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('loans', 'tenure_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('loans', 'sanction_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('loans', 'sanction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('loans', 'institution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('loans', 'loan_number')
    # ### end Alembic commands ###
